# Basic Information
title: "Yongfa (Jay) You"
position: "<span style='color: purple;'>Postdoc, Boston College <br> Assistant Professor, Virginia Tech</span>"
email: "<span style='font-size: 16px; font-family: Arial, sans-serif; font-weight: bold;'>yongfayou@vt.edu</span>"
email2: "" # Add a secondary email if needed
address: "" # Physical address
address_link: "" # Link to Google Maps or similar

# Search Engine Optimization (SEO)
keywords:
  - yongfa you
  - you yongfa
  - yongfayou
  - youyongfa
canonical: "https://minimal-light-theme.yliu.me/"
description: >
  Yongfa You is currently a Postdoctoral Research Fellow at Boston College and will join Virginia Tech as a tenure-track Assistant Professor in June 2025. His research focuses on 
  climate-smart agriculture, Earth system modeling, sustainable land management practices, 
  and geospatial data science.

# Special Options
enable_hopkins_logo: false # Enable/disable the Johns Hopkins template
enable_last_update: false # Show/hide the last update time on pages

# Links
google_scholar: "https://scholar.google.com/citations?user=Bd5il3oAAAAJ&hl=en"
twitter: "https://x.com/yongfa_you"

# Images
avatar: "./assets/img/Yongfa You_Life Picture1.jpg"
favicon: "./assets/img/Yongfa You_Life Picture1.jpg"
favicon_dark: "./assets/img/Yongfa You_Life Picture1.jpg"

# Footnotes
enable_footnote: false # Disable "Powered by Jekyll and Minimal Light theme"
# Uncomment below to customize the footnote
# footnote: "Feel free to use my website's source code."
# footnote_link: "https://github.com/yaoyao-liu/minimal-light"

# Google Analytics
# Remove this line if Google Analytics is not used
google_analytics: "${{ secrets.GOOGLE_SCHOLAR_ID }}"

# Jekyll Theme
remote_theme: "yaoyao-liu/minimal-light"
plugins:
  - jekyll-remote-theme # Required for remote themes

# Excluded Files
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
