main:
  - title: BeMAGIC Final Event - Post Event
    authors: Song Chen
    conference_short: BeMAGIC
    conference: BeMAGIC Final Event
    pdf: https://bemagic-etn.eu/images/files2023/BeMAGIC%20Final%20Event%20information%201.pdf
    web: https://bemagic-etn.eu/news/81-bemagic-final-event-post-event
    image: ./assets/img/autova.png
    notes: 

  - title: Reversible and Non-volatile Magneto-ionic effect in W-CoFeB-MgO-HfO2 ultra-thin films with Perpendicular Anisotropy
    authors: Song Chen, Elmer Monteblanco, Rohit Pachat, Liza Herrera Diez, Dafiné Ravelosona
    conference_short: JEMS
    conference: 13th Joint European Magnetic Symposia
    pdf: ./assets/files/JEMS2023_Song.pdf
    web: https://www.jems2023.es/
    image: ./assets/files/JEMS2023_2.jpg
    notes: Accepted

  - title: BeMAGIC CONFERENCE IN TORINO – POST EVENT
    conference_short: BeMAGIC
    conference: BeMAGIC CONFERENCE IN TORINO
    abstract: The BeMAGIC conference in Torino, entitled “Beyond Magnetoelectric Materials”, was successfully organized by the network ESRs (Early Stage Researchers). This event took place on 12-15 June 2023 at the Starhotel Majestic, Torino, Italy. The programme included 15 top-class experts in the magnetoelectric field, who delivered lectures on the following topics&#58; multiferroics, surface charging, magnetoionics and applications in healthcare, energy efficiency and cybersecurity.
    pdf: https://bemagic-etn.eu/images/files2023/BeMAGIC_Conference_Torino_2023.pdf
    web: https://bemagic-etn.eu/news/79-bemagic-conference-in-torino-2023-post-event
    image: ./assets/img/Group_picture.jpg

  - title: BeMAGIC Winter School - ETH Zürich
    conference_short: BeMAGIC
    conference:  BeMAGIC Winter School&#58; Magnetoelectricity in biomedicine healthcare for the 21st century ETH Zürich
    abstract: The BeMAGIC Winter School, entitled&#58; “Magnetoelectricity in biomedicine&#58; healthcare for the 21st century”, took place in Zurich from November 8 to 12, 2021. 
    #pdf: https://bemagic-etn.eu/images/files2021/BeMAGIC_Winter_School_ETHZ_agenda.pdf
    web: https://bemagic-etn.eu/news/68-bemagic-winter-school-post-event
    image: ./assets/img/eth.jpg

  - title: JOINT WORKSHOP BEMAGIC / MAGNEFI AT AALTO UNIVERSITY
    conference_short: BeMAGIC
    conference:  BeMAGIC Winter School&#58; Magnetoelectricity in biomedicine healthcare for the 21st century ETH Zürich
    abstract: The BeMAGIC workshop at AALTO University (Helsinki, Finland), co-organized with the MagnEFi network, took place from 13 to 17 June 2022.  
    #pdf: https://bemagic-etn.eu/images/files2021/BeMAGIC_Winter_School_ETHZ_agenda.pdf
    web: https://bemagic-etn.eu/news/73-joint-workshop-bemagic-magnefi-at-aalto-university-post-event
    image: ./assets/img/joint.jpg

  - title: BeMAGIC Summer School&#58; Setting gateway to academia (UCAM)
    conference_short: BeMAGIC
    conference:  BeMAGIC Winter School&#58; Magnetoelectricity in biomedicine healthcare for the 21st century ETH Zürich
    abstract: The next BeMAGIC workshop, organized by the University of Cambridge, will take place online on 7-9 April 2021 (workshop) and 10-11 May 2021 (training in soft skills).   
    #pdf: https://bemagic-etn.eu/images/files2021/BeMAGIC_Winter_School_ETHZ_agenda.pdf
    web: https://bemagic-etn.eu/news/62-bemagic-summer-school-post-event
    image: ./assets/img/Portada-cc58d654.jpg

  - title: BeMAGIC WORKSHOP AT GTECM
    conference_short: BeMAGIC
    conference:  BEMAGIC Workshop - Gateway to industry&#58;innovation, entrepreneurship and marketable products using ME technology
    abstract: The BeMAGIC Workshop at GTECM was successfuly organized in Innsbruck, Austria, from 13 to 16 December 2022.
    pdf: https://bemagic-etn.eu/images/files2022/BeMagic_Workshop_GTECM_agenda.pdf
    web: https://bemagic-etn.eu/news/77-bemagic-workshop-at-gtecm-post-event
    image: ./assets/img/lF0ulCNA.jpeg

